name: CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install  Nix
        uses: cachix/install-nix-action@v14
        with:
          install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.5pre20211015_130284b/install
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Check marp builds
        run: nix build

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install  Nix
        uses: cachix/install-nix-action@v14
        with:
          install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.5pre20211015_130284b/install
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Check nixpkgs-fmt formatting
        run: nix-shell --run "find . -path '*.nix' ! -iname 'default.nix' ! -iname 'node-env.nix' -print0 | xargs -0 nixpkgs-fmt --check"

  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install  Nix
        uses: cachix/install-nix-action@v14
        with:
          install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.5pre20211015_130284b/install
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Check codespell
        run: nix-shell --run "find . -path '*.sh' -print0 | xargs -0 codespell --exclude-file node-packages.nix"

